educational_manager/educational_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('teacher/', include('teacher.urls')),
]

educational_manager/teacher/urls.py
from django.urls import path

from . import views

app_name = "teacher"
urlpatterns = [
    path('home/', views.home, name="teacherHome"),
    path('get_standards/', views.getStandards, name="getStandards"),
    path('know_show_chart/', views.knowShowChart, name="knowShowChart"),
    path('save_know_show_chart/', views.saveKnowShowChart, name="saveKnowShowChart"),
    path('assessment_developer/<str:pk>/<str:assessment_id>', views.assessmentDeveloper, name="assessmentDeveloper"),
    path('save_question/<str:pk>/<str:assessment_id>', views.saveQuestion, name="saveQuestion"),
    path('create/', views.create, name="create"),
    path('know_show_selector/', views.knowShowSelector, name="knowShowSelector"),
    path('get_know_show/<str:code>/', views.getKnowShow, name="getKnowShow"),
    path('instantiate_assessment/<str:pk>/', views.createAssessment, name="createAssessment")
    ]

educational_manager/teacher/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Prep(models.Model):
    title = models.CharField(max_length=200)
    subject = models.CharField(max_length=20, choices=(("Math", "Math"),
                                                       ("Science", "Science"),
                                                       ("English", "English"),
                                                       ("Social Studies", "Social Studies"),
                                                       ("Elective", "Elective"),
                                                       ))
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class ScopeAndSequence(models.Model):
    subject = models.CharField(max_length=20, choices=(("Math", "Math"),
                                                       ("Science", "Science"),
                                                       ("English", "English"),
                                                       ("Social Studies", "Social Studies"),
                                                       ("Elective", "Elective"),
                                                       ))
    grade_level = models.CharField(max_length=200)
    content = models.JSONField()


class Course(models.Model):
    prep = models.ForeignKey(Prep, on_delete=models.CASCADE)
    period = models.IntegerField()


class Standard(models.Model):
    code = models.CharField(max_length=200)
    text = models.CharField(max_length=200)
    subject = models.CharField(max_length=20, choices=(("Math", "Math"),
                                                       ("Science", "Science"),
                                                       ("English", "English"),
                                                       ("Social Studies", "Social Studies"),
                                                       ("Elective", "Elective"),
                                                       ))

    def __str__(self):
        return self.code


class KnowShowChart(models.Model):
    content = models.JSONField()
    standard = models.ForeignKey(Standard, on_delete=models.CASCADE)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateField(auto_now_add=True)

    def get_assessments(self):
        return self.assessment_set.all()

    def __str__(self):
        return f'{self.standard} created by {self.creator} on {self.created}'


class Assessment(models.Model):
    know_show_chart = models.ForeignKey(KnowShowChart, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)

    def get_standard(self):
        return self.know_show_chart.standard

    def get_questions(self):
        return self.question_set.all()


class Question(models.Model):
    assessment = models.ForeignKey(Assessment, on_delete=models.CASCADE)
    satisfied = models.JSONField()
    text = models.CharField(max_length=200)
    created = models.DateField(auto_now_add=True)

    def get_standard(self):
        return self.assessment.know_show_chart.standard

    def get_answers(self):
        return self.answer_set.all()

    def __str__(self):
        return self.text


class Answer(models.Model):
    text = models.CharField(max_length=200)
    correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return f"question: {self.question}, answer: {self.text}, correct: {self.correct}"

educational_manager/teacher/views.py
from django.shortcuts import render, redirect
from .models import Standard, KnowShowChart, Assessment, Question, Answer
from django.apps import apps
from django.http import JsonResponse
import json


User = apps.get_model('users', 'User')
# Create your views here.
def home(request):
    standard_list = Standard.objects.all()
    context = {
        "standard_list": standard_list,
    }
    return render(request, 'teacher/home.html', context)


def knowShowChart(request):
    standardCodes = Standard.objects.all()

    context = {'standardCodes': standardCodes}
    return render(request, 'teacher/knowShowChart.html', context)


def getStandards(request):
    standard_list = list(Standard.objects.values())
    return JsonResponse({"standard_list": standard_list})


def saveKnowShowChart(request):
    know_list = [request.POST[key] for key in request.POST if 'know' in key and request.POST[key] != '']
    show_list = [request.POST[key] for key in request.POST if 'show' in key and request.POST[key] != '']
    scaffold_list = [request.POST[key] for key in request.POST if 'scaffold' in key and request.POST[key] != '']
    standard = Standard.objects.get(code=request.POST['standardsDropDown'])
    if request.method == 'POST':
        content = json.dumps({
            'know': know_list,
            'show': show_list,
            'scaffold': scaffold_list,
        })
        chart = KnowShowChart(content=content, standard=standard, creator=request.user)
        chart.save()
    return redirect('teacher:knowShowChart')


def assessmentDeveloper(request, pk, assessment_id):
    know_show_chart = KnowShowChart.objects.get(id=pk)
    assessment = Assessment.objects.get(id=assessment_id)
    content = json.loads(know_show_chart.content)
    know_requirement = content['know']
    show_requirement = content['show']

    know_satisfied = []
    show_satisfied = []
    questions_list = assessment.get_questions()
    for question in questions_list:
        k_sat = json.loads(question.satisfied)['know']
        s_sat = json.loads(question.satisfied)['show']
        for i in k_sat:
            know_satisfied.append(i)
        for i in s_sat:
            show_satisfied.append(i)
    know_remaining = [x for x in know_requirement if x not in know_satisfied]
    show_remaining = [x for x in show_requirement if x not in show_satisfied]
    if know_remaining or show_remaining:
        question_number = len(questions_list) + 1

        context = {
            'knowSatisfied': know_satisfied,
            'showSatisfied': show_satisfied,
            'knowRemaining': know_remaining,
            'showRemaining': show_remaining,
            'questionNumber': question_number,
            'ksid': pk,
            'aid': assessment_id,
        }
        return render(request, 'teacher/assessmentDeveloper.html', context)

    else:
        return redirect('teacher:teacherHome')


def saveQuestion(request, pk, assessment_id):
    assessment = Assessment.objects.get(id=assessment_id)
    know_show_chart = KnowShowChart.objects.get(id=pk)
    content = json.loads(know_show_chart.content)
    know_requirement = content['know']
    show_requirement = content['show']
    know_satisfied = []
    show_satisfied = []
    queryDict = dict(request.POST)
    for key in queryDict:
        if queryDict[key] == ['on']:
            if key in know_requirement:
                know_satisfied.append(key)
            elif key in show_requirement:
                show_satisfied.append(key)
    satisfied_json = json.dumps({'know': know_satisfied, 'show': show_satisfied})
    new_question = Question(text=request.POST['question-text'], assessment=assessment, satisfied=satisfied_json)
    new_question.save()
    for key in queryDict:
        if 'answer' in key:
            if key == f'{queryDict["correct"][0]}-text':
                new_answer = Answer(text=request.POST[key], question=new_question, correct=True)
                new_answer.save()
            elif key != f'{queryDict["correct"][0]}-text':
                new_answer = Answer(text=request.POST[key], question=new_question, correct=False)
                new_answer.save()

    return redirect('teacher:assessmentDeveloper', pk, assessment_id)


def createAssessment(request, pk):
    know_show_chart = KnowShowChart.objects.get(id=pk)
    list_of_assessments = know_show_chart.get_assessments()
    new_assessment = Assessment(know_show_chart=know_show_chart,
                                title=f"ksid{know_show_chart.id}:{know_show_chart.standard.code} {len(list_of_assessments) + 1}")
    new_assessment.save()
    assessment_id = new_assessment.id
    return redirect('teacher:assessmentDeveloper', pk, assessment_id)

def create(request):
    return render(request, 'teacher/create.html')


def knowShowSelector(request):
    standard_codes = Standard.objects.all()
    context = {
        'standardCodes': standard_codes,
    }
    return render(request, 'teacher/knowShowSelector.html', context)


def getKnowShow(request, code):
    charts_query = list(KnowShowChart.objects.filter(standard=code).values())
    for know_show in charts_query:
        know_show['creator'] = f"{User.objects.get(id=know_show['creator_id']).first_name} {User.objects.get(id=know_show['creator_id']).last_name}"
    print(charts_query)
    return JsonResponse({'charts_query': charts_query})

educational_manager/teacher/templates/teacher/assessmentDeveloper.html
{% extends 'teacher/base.html' %}
{% load static %}

{% block title %}
Assessment Developer
{% endblock title %}

{% block scripts %}
<script src={% static 'assessmentDeveloper.js' %} defer></script>
{% endblock scripts %}

{% block content %}
    <form method="POST" id="assessmentBuilder" name="assessmentBuilder" action="{% url 'teacher:saveQuestion' ksid aid %}">
    {% csrf_token %}
    <div class="know-show-display">
        <h1 class="center center-text">Know - Show Chart</h1>
        <div class="know-list">
            <ul style="list-style: none">
            {% for know in knowRemaining %}
                <li><input type="checkbox" form="assessmentBuilder" id="{{ know }}" name="{{ know }}">{{ know }}</li>
            {% endfor %}
            {% for know in knowSatisfied %}
                <li><strike>{{ know }}</strike></li>
            {% endfor %}
            </ul>
        </div>
        <div class="show-list">
            <ul style="list-style: none">
                {% for show in showRemaining %}
                    <li><input type="checkbox" form="assessmentBuilder" id="{{ show }}" name="{{ show }}">{{ show }}</li>
                {% endfor %}
                {% for show in showSatisfied %}
                    <li><strike>{{ show }}</strike></li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div style="float: left; margin-left: 4%">
        <h3>Question {{ questionNumber }}:</h3>
        <textarea rows="8" cols="60" form="assessmentBuilder" name="question-text"></textarea>
        <h3>Answers:</h3>
        <div id="answers-div">
            <table id="answers-table">

            </table>



        </div>
        <button class="add-button" type="button" onclick="add_item(this)" name="answers">+</button>
    </div>
        <input type="submit" value="Save Question">
    </form>
{% endblock content %}

educational_manager/teacher/templates/teacher/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Teacher | {% block title %}{% endblock title %}</title>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

    <link rel="stylesheet" href={% static "teacher.css" %}/>

    {% block scripts %}
    {% endblock scripts %}

</head>
<body>
    <div class="header" id="header">
        <h1 style="display: inline-block">Welcome, {{ request.user.first_name }}!</h1>
        <a href="{% url 'teacher:knowShowChart' %}"><button class="dash-button" type="button">Data</button></a>
        <a href="{% url 'teacher:knowShowChart' %}"><button class="dash-button" type="button">Assign</button></a>
        <a href="{% url 'teacher:create' %}"><button class="dash-button" type="button">Create</button></a>
        <a href="{% url 'teacher:teacherHome' %}"><button class="dash-button" type="button">Home</button></a>

    </div>
    <div>
        {% block content %}
        {% endblock content %}
    </div>


</body>
</html>

educational_manager/teacher/templates/teacher/create.html
{% extends 'teacher/base.html' %}
{% load static %}

{% block title %}
Create
{% endblock title %}

{% block scripts %}
<script src={% static 'create.js' %} defer></script>
{% endblock scripts %}

{% block content %}
    <div class="container">
    <table style="margin-top: 5%;" class="center">
        <tr>
            <td style="padding:10px">
                <div>
                    <a href="{% url 'teacher:knowShowChart' %}">
                        <button>
                            <img class="button-label" src="https://ucarecdn.com/926942c0-0b7a-46f0-ac60-a1ef13090620/KnowShowChart.png"/>
                        </button>
                    </a>
                </div>
            </td>
            <td style="padding:10px">
                <div>
                    <a href="{% url 'teacher:knowShowSelector' %}">
                        <button>
                            <img class="button-label" src="https://ucarecdn.com/7ba4632e-3319-4153-8ce2-31ca33582832/Assessment.png"/>
                        </button>
                    </a>
                </div>
            </td>
            <td style="padding:10px">
                <div>
                    <a href="{% url 'teacher:knowShowSelector' %}">
                        <button>
                            <img class="button-label" src="https://ucarecdn.com/1ccd698a-3f15-452d-a52e-45b245338dc1/Enrollments.png"/>
                        </button>
                    </a>
                </div>
            </td>
        </tr>
    </table>

    </div>
{% endblock content %}

educational_manager/teacher/templates/teacher/home.html
{% extends 'teacher/base.html' %}
{% load static %}

{% block title %}
home
{% endblock title %}

{% block scripts %}
<script src={% static 'teacher.js' %} defer></script>
{% endblock scripts %}

{% block content %}
    {% for standard in standard_list %}
    <div id="standardSpace">
    </div>
    {% endfor %}
{% endblock content %}

educational_manager/teacher/templates/teacher/knowShowChart.html
{% extends 'teacher/base.html' %}
{% load static %}

{% block title %}
Know Show Chart
{% endblock title %}

{% block scripts %}
<script src={% static 'knowShowChart.js' %} defer></script>
{% endblock scripts %}

{% block content %}
<form id="chartBuilder" name="chartBuilder" method="POST" action="{% url 'teacher:saveKnowShowChart' %}">
{% csrf_token %}
    <select onchange="standardContentDisplay()" id="standardsDropDown" name="standardsDropDown" form="chartBuilder">
        <option selected disabled value="1">Select a Standard</option>
        {% for code in standardCodes %}
        <option value="{{ code }}">{{ code }}</option>
        {% endfor %}
    </select>
    <p style="position: absolute" id="display-text">^^Choose a Standard^^</p>
    {% for code in standardCodes %}
    <p style="position: absolute" class="hidden" id="{{ code }}">{{ code.text }}</p>
    {% endfor %}
    <div class="center" id="container-div">
        <table class="center">
            <tr>
                <td style="vertical-align: top">
                    <div class="center" id="section1">

                        <div style='width: 100%;' class="popup" onclick="popupDisplay('know-pop')"><h1 class="center center-text">Know</h1>
                            <span class="popuptext" id="know-pop">Know entries should be full sentences representing the information students should learn and retain through the course of learning this standard.</span>
                        </div>
                        <div class="center" id="know-div">
                            <textarea class="center" id="know1" name="know1" form="chartBuilder" onkeyup="if (this.scrollHeight > this.clientHeight) this.style.height = this.scrollHeight + 'px';"></textarea>
                        </div>
                        <button class="center block add-button" type="button" onClick="add_item(this)" name="know">+</button>
                    </div>
                </td>
                <td style="vertical-align: top">
                    <div class="center" id="section2">
                         <div style='width: 100%;' class="popup" onclick="popupDisplay('show-pop')"><h1 class="center center-text">Show</h1>
                            <span class="popuptext" id="show-pop">Show entries should be 'I can...' statements indicating skills that students will develop through the course of learning this standard.</span>
                        </div>
                        <div class="center" id="show-div">
                            <textarea class="center" id="show1" name="show1" form="chartBuilder" onkeyup="if (this.scrollHeight > this.clientHeight) this.style.height = this.scrollHeight + 'px';"></textarea>
                        </div>
                        <button class="center block add-button" type="button" onClick="add_item(this)" name="show">+</button>
                    </div>
                </td>
                <td style="vertical-align: top">
                    <div class="center" id="section3">
                        <div style='width: 100%;' class="popup" onclick="popupDisplay('scaffold-pop')"><h1 class="center center-text">Scaffold</h1>
                            <span class="popuptext" id="scaffold-pop">Scaffold entries should be knowledge and skills that students need to have mastered previously in order to succeed in learning this standard. This list is purely for planning and will not be incorporated into the assessment design workflow.</span>
                        </div>
                        <div class="center" id="scaffold-div">
                            <textarea class="center" id="scaffold1" name="scaffold1" form="chartBuilder" onkeyup="if (this.scrollHeight > this.clientHeight) this.style.height = this.scrollHeight + 'px';"></textarea>
                        </div>
                        <button class="center block add-button" type="button" onClick="add_item(this)" name="scaffold">+</button>
                    </div>
                </td>
            </tr>
        </table>



    </div>
<input class="center" type="submit">
</form>
{% endblock content %}

educational_manager/teacher/templates/teacher/knowShowSelector.html
{% extends 'teacher/base.html' %}
{% load static %}

{% block title %}
Select a Know Show Chart
{% endblock title %}

{% block scripts %}
<script src={% static 'knowShowSelector.js' %} defer></script>
{% endblock scripts %}

{% block content %}
    <div class="container">
    <select onchange="standardContentDisplay()" id="standardsDropDown" name="standardsDropDown" form="chartBuilder">
        <option selected disabled value="1">Select a Standard</option>
        {% for code in standardCodes %}
        <option value="{{ code.id }}">{{ code }}</option>
        {% endfor %}
    </select>
    <p style="position: absolute" id="display-text">^^Choose a Standard^^</p>
    {% for code in standardCodes %}
    <p style="position: absolute" class="hidden" id="{{ code.id }}">{{ code.text }}</p>
    {% endfor %}
    <div class="chart-container" id="chart-container">

    </div>
{% endblock content %}